// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjDWIItLg4RihsM6KqH6N7P1dKWJ7e1Q',
    appId: '1:816577151451:web:96cfde0c3eb448bce8e7fe',
    messagingSenderId: '816577151451',
    projectId: 'techtrake-ea7a0',
    authDomain: 'techtrake-ea7a0.firebaseapp.com',
    storageBucket: 'techtrake-ea7a0.appspot.com',
    measurementId: 'G-E59ZZ3QX5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNt0qR_TdvgySJzF-JYNiNQ2y7YDjL--8',
    appId: '1:816577151451:android:db860e6f32036563e8e7fe',
    messagingSenderId: '816577151451',
    projectId: 'techtrake-ea7a0',
    storageBucket: 'techtrake-ea7a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fnd8Sp85aZU-cLGpXqgCc23fYLtKZO8',
    appId: '1:816577151451:ios:13cf4f2213d8d89ae8e7fe',
    messagingSenderId: '816577151451',
    projectId: 'techtrake-ea7a0',
    storageBucket: 'techtrake-ea7a0.appspot.com',
    iosBundleId: 'com.example.teachtrake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7fnd8Sp85aZU-cLGpXqgCc23fYLtKZO8',
    appId: '1:816577151451:ios:13cf4f2213d8d89ae8e7fe',
    messagingSenderId: '816577151451',
    projectId: 'techtrake-ea7a0',
    storageBucket: 'techtrake-ea7a0.appspot.com',
    iosBundleId: 'com.example.teachtrake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLjDWIItLg4RihsM6KqH6N7P1dKWJ7e1Q',
    appId: '1:816577151451:web:0ae3278c4e2b3c4fe8e7fe',
    messagingSenderId: '816577151451',
    projectId: 'techtrake-ea7a0',
    authDomain: 'techtrake-ea7a0.firebaseapp.com',
    storageBucket: 'techtrake-ea7a0.appspot.com',
    measurementId: 'G-S72563JBNK',
  );

}